name: Scrape Scholar Data

on:
  # schedule:
    # - cron: '0 0 * * *'  # Runs at 00:00 UTC every day.
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }} # Use the PAT for checkout
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
    - name: Run scraper
      run: python DataParser.py
    - name: Commit and push if changes
      run: |
        git config --global user.name 'jinningwang'
        git config --global user.email 'jinninggm@gmail.com'
        git add -A
        git diff --staged --quiet || git commit -m "Update Google Scholar data"
        git push --set-upstream origin master
